const PLACEHOLDER_LOCATION = 'Локация для тура';
const PLACEHOLDER_DATE = 'Дата похода';
const PLACEHOLDER_PARTICIPANTS = 'Участники';

export {
  PLACEHOLDER_LOCATION,
  PLACEHOLDER_DATE,
  PLACEHOLDER_PARTICIPANTS
};
